import type { Metadata } from 'next'
import { Roboto_Flex as Roboto, Ms_Madi as MsMadi } from 'next/font/google'

import './globals.css'
import { ThemeProviders } from './theme-provider'
import Header from '@/components/header'
import Footer from '@/components/footer'
import Background from '@/components/background'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
})

const msmadi = MsMadi({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-msmadi',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${roboto.variable} ${msmadi.variable} overflow-x-hidden`}
      >
        <ThemeProviders>
          <Header />
          <Background />
          {children}
          <Footer />
        </ThemeProviders>
      </body>
    </html>
  )
}
