name: Deploy to Locaweb FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Build the project
        run: |
          npm run build

      - name: FTP Deploy to Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./next  # Aqui define a pasta local para o upload
          remote-dir: /home/sandrodev1/public_html  # Defina o diretório correto aqui
          force-ssl: true  # Caso necessário
