name: Deploy via FTP

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.17.0 # Certifique-se de usar uma versão compatível com o Next.js

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build
      env:
        NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
        NEXT_PUBLIC_EMAILJS_ID: ${{ secrets.NEXT_PUBLIC_EMAILJS_ID }}
        NEXT_PUBLIC_EMAILJS_TEMPLATE: ${{ secrets.NEXT_PUBLIC_EMAILJS_TEMPLATE }}
        NEXT_PUBLIC_PUBLICKEY: ${{ secrets.NEXT_PUBLIC_PUBLICKEY }}
        APP_URL: ${{ secrets.APP_URL }}

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: ".next"
       
