name: Deploy via FTP

on:
  push:
    branches:
      - main # Ou o branch que você usa para deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16 # Altere para a versão do Node.js que você está usando

    - name: Install dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: ".next" # Diretório onde o Next.js gera os arquivos de build
        remoteDir: "public_html" # Diretório remoto no servidor FTP
